### ISSUE TITLE
Discojs is not exported by default

### ISSUE THREAD

**Issue by iltimasd** [aknorw/discojs#29]
Documentation has the import as follows:

```js
  import Discojs  from "discojs";
```

but the above returns the following type error: `TypeError: Discojs__default.default is not a constructor`

current fix is to import the fn/constructor by name:

```js
  import {Discojs}  from "discojs";
```

**Comment by aknorw** [comment]
My bad, missed this one when updating the documentation - but named export is the way now. Will change it asap.
