### ISSUE TITLE
Can't use import

### ISSUE THREAD

**Issue by Cryopt** [aknorw/discojs#44]
Hey,
When I use import in my file an error shows up `cannot use import statement outside a module`.  I made some researches and I still don't really understand why I have this error. Can I use this without using import ?
Thanks

**Comment by neurowelt** [comment]
Hi,
I just started getting familiar with this library and [this thread](https://stackoverflow.com/questions/58384179/syntaxerror-cannot-use-import-statement-outside-a-module) helped me out.
Specifically, add `"type":"module"` to your `package.json` file and then you should be able to get going like this:
```
import Discojs from 'Discojs';

const client = new Discojs.Discojs({
   //options
})
```
Hope this helps 🙂
