### ISSUE TITLE
Problems with core-js dependency

### ISSUE THREAD

**Issue by AlainGourves** [aknorw/discojs#7]
I got errors with the current version of `core-js` (v3.0.1) and had to install an old version (v2.6.5) to make `discojs` running.
Apparently there was some important changes between branch 2 and 3 of `core-js`, in particular `core-js/modules/es6.promise` disappeared which `discojs` rely upon.

**Comment by aknorw** [comment]
Thanks for the issue, I will update the package with `core-js@3` asap (as well as updating all the outdated dependencies).

**Comment by aknorw** [comment]
Version 1.2.0 was released, this issue should be resolved.
